"""Static signatures for the common worksheet functions.

The runtime builds calls through ``__getattr__``, so no checker can see how many
arguments ``F.SUMIF`` wants.  Declaring the common ones here moves the arity check
from run time to edit time, while the ``__getattr__`` fallback keeps every other
name -- add-ins, new releases -- typing cleanly with any arguments.

Positions that must be a reference are typed ``Expr`` rather than ``_Value``, so
passing the *string* ``"A:A"`` where a range belongs is rejected: it would render as
a text literal, not a range.  Everything else stays ``_Value``, because ``None`` is
a legal *omitted argument* in any position and any value may arrive as a computed
expression -- narrowing a parameter to ``int`` or ``bool`` rejects both.  Where a
signature is uncertain, prefer the permissive type: a false error here is worse
than a missed one.
"""

import datetime as _dt
from collections.abc import Callable
from decimal import Decimal
from typing import TypeAlias

from .expr import Expr

__all__ = ["Func", "F", "UnknownFunctionWarning"]

# Anything lit() can render.  Expr is a str subclass, so it is covered by `str`,
# but naming it makes the intent readable at each call site.
_Value: TypeAlias = Expr | str | int | float | bool | Decimal | _dt.date | _dt.time | _dt.datetime | None

class UnknownFunctionWarning(UserWarning): ...

_XLFN: frozenset[str] | set[str]
_XLWS: frozenset[str] | set[str]
_KNOWN: frozenset[str]
_ARITY: dict[str, tuple[int, int | None]]

def stored_name(name: str) -> str: ...

class Func(Expr):
    name: str
    args: tuple[Expr, ...]
    def __new__(cls, name: str, *args: _Value, check: bool = ...) -> Func: ...
    def shift(self, rows: int = ..., cols: int = ...) -> Func: ...

class _Functions:
    # -- aggregation ------------------------------------------------------------
    def SUM(self, value: _Value, /, *values: _Value, check: bool = ...) -> Func: ...
    def SUMIF(self, range: Expr, criteria: _Value, sum_range: Expr = ..., /, *, check: bool = ...) -> Func: ...
    def SUMIFS(
        self, sum_range: Expr, criteria_range: Expr, criteria: _Value, /, *more: _Value, check: bool = ...
    ) -> Func: ...
    def SUMPRODUCT(self, array: Expr, /, *arrays: Expr, check: bool = ...) -> Func: ...
    def AVERAGE(self, value: _Value, /, *values: _Value, check: bool = ...) -> Func: ...
    def AVERAGEIF(self, range: Expr, criteria: _Value, average_range: Expr = ..., /, *, check: bool = ...) -> Func: ...
    def AVERAGEIFS(
        self, average_range: Expr, criteria_range: Expr, criteria: _Value, /, *more: _Value, check: bool = ...
    ) -> Func: ...
    def COUNT(self, value: _Value, /, *values: _Value, check: bool = ...) -> Func: ...
    def COUNTA(self, value: _Value, /, *values: _Value, check: bool = ...) -> Func: ...
    def COUNTBLANK(self, range: Expr, /, *, check: bool = ...) -> Func: ...
    def COUNTIF(self, range: Expr, criteria: _Value, /, *, check: bool = ...) -> Func: ...
    def COUNTIFS(self, criteria_range: Expr, criteria: _Value, /, *more: _Value, check: bool = ...) -> Func: ...
    def MIN(self, value: _Value, /, *values: _Value, check: bool = ...) -> Func: ...
    def MAX(self, value: _Value, /, *values: _Value, check: bool = ...) -> Func: ...
    def MAXIFS(
        self, max_range: Expr, criteria_range: Expr, criteria: _Value, /, *more: _Value, check: bool = ...
    ) -> Func: ...
    def MINIFS(
        self, min_range: Expr, criteria_range: Expr, criteria: _Value, /, *more: _Value, check: bool = ...
    ) -> Func: ...
    def MEDIAN(self, value: _Value, /, *values: _Value, check: bool = ...) -> Func: ...

    # -- arithmetic -------------------------------------------------------------
    def ROUND(self, number: _Value, num_digits: _Value, /, *, check: bool = ...) -> Func: ...
    def ROUNDUP(self, number: _Value, num_digits: _Value, /, *, check: bool = ...) -> Func: ...
    def ROUNDDOWN(self, number: _Value, num_digits: _Value, /, *, check: bool = ...) -> Func: ...
    def ABS(self, number: _Value, /, *, check: bool = ...) -> Func: ...
    def MOD(self, number: _Value, divisor: _Value, /, *, check: bool = ...) -> Func: ...
    def INT(self, number: _Value, /, *, check: bool = ...) -> Func: ...
    def POWER(self, number: _Value, power: _Value, /, *, check: bool = ...) -> Func: ...
    def SQRT(self, number: _Value, /, *, check: bool = ...) -> Func: ...

    # -- logic ------------------------------------------------------------------
    def IF(self, test: _Value, if_true: _Value, if_false: _Value = ..., /, *, check: bool = ...) -> Func: ...
    def IFERROR(self, value: _Value, if_error: _Value, /, *, check: bool = ...) -> Func: ...
    def IFNA(self, value: _Value, if_na: _Value, /, *, check: bool = ...) -> Func: ...
    def IFS(self, test: _Value, value: _Value, /, *pairs: _Value, check: bool = ...) -> Func: ...
    def AND(self, test: _Value, /, *tests: _Value, check: bool = ...) -> Func: ...
    def OR(self, test: _Value, /, *tests: _Value, check: bool = ...) -> Func: ...
    def NOT(self, test: _Value, /, *, check: bool = ...) -> Func: ...
    def SWITCH(
        self, expression: _Value, value: _Value, result: _Value, /, *cases: _Value, check: bool = ...
    ) -> Func: ...

    # -- lookup -----------------------------------------------------------------
    def VLOOKUP(self, key: _Value, table: Expr, col: _Value, exact: _Value = ..., /, *, check: bool = ...) -> Func: ...
    def HLOOKUP(self, key: _Value, table: Expr, row: _Value, exact: _Value = ..., /, *, check: bool = ...) -> Func: ...
    def INDEX(
        self, array: Expr, row: _Value, column: _Value = ..., area: _Value = ..., /, *, check: bool = ...
    ) -> Func: ...
    def MATCH(self, key: _Value, array: Expr, match_type: _Value = ..., /, *, check: bool = ...) -> Func: ...
    def OFFSET(
        self,
        reference: Expr,
        rows: _Value,
        cols: _Value,
        height: _Value = ...,
        width: _Value = ...,
        /,
        *,
        check: bool = ...,
    ) -> Func: ...
    def INDIRECT(self, ref_text: _Value, a1: _Value = ..., /, *, check: bool = ...) -> Func: ...
    def CHOOSE(self, index: _Value, value: _Value, /, *values: _Value, check: bool = ...) -> Func: ...
    def XLOOKUP(
        self,
        key: _Value,
        lookup: Expr,
        result: Expr,
        if_not_found: _Value = ...,
        match_mode: _Value = ...,
        search_mode: _Value = ...,
        /,
        *,
        check: bool = ...,
    ) -> Func: ...
    def XMATCH(
        self, key: _Value, lookup: Expr, match_mode: _Value = ..., search_mode: _Value = ..., /, *, check: bool = ...
    ) -> Func: ...
    def ROW(self, reference: Expr = ..., /, *, check: bool = ...) -> Func: ...
    def COLUMN(self, reference: Expr = ..., /, *, check: bool = ...) -> Func: ...

    # -- dynamic arrays ---------------------------------------------------------
    def FILTER(self, array: Expr, include: _Value, if_empty: _Value = ..., /, *, check: bool = ...) -> Func: ...
    def SORT(
        self,
        array: Expr,
        sort_index: _Value = ...,
        sort_order: _Value = ...,
        by_col: _Value = ...,
        /,
        *,
        check: bool = ...,
    ) -> Func: ...
    def UNIQUE(
        self, array: Expr, by_col: _Value = ..., exactly_once: _Value = ..., /, *, check: bool = ...
    ) -> Func: ...
    def SEQUENCE(
        self, rows: _Value, columns: _Value = ..., start: _Value = ..., step: _Value = ..., /, *, check: bool = ...
    ) -> Func: ...

    # -- text -------------------------------------------------------------------
    def TEXT(self, value: _Value, format_text: _Value, /, *, check: bool = ...) -> Func: ...
    def LEN(self, text: _Value, /, *, check: bool = ...) -> Func: ...
    def LEFT(self, text: _Value, num_chars: _Value = ..., /, *, check: bool = ...) -> Func: ...
    def RIGHT(self, text: _Value, num_chars: _Value = ..., /, *, check: bool = ...) -> Func: ...
    def MID(self, text: _Value, start: _Value, num_chars: _Value, /, *, check: bool = ...) -> Func: ...
    def TRIM(self, text: _Value, /, *, check: bool = ...) -> Func: ...
    def UPPER(self, text: _Value, /, *, check: bool = ...) -> Func: ...
    def LOWER(self, text: _Value, /, *, check: bool = ...) -> Func: ...
    def SUBSTITUTE(
        self, text: _Value, old: _Value, new: _Value, instance: _Value = ..., /, *, check: bool = ...
    ) -> Func: ...
    def FIND(self, find_text: _Value, within: _Value, start: _Value = ..., /, *, check: bool = ...) -> Func: ...
    def SEARCH(self, find_text: _Value, within: _Value, start: _Value = ..., /, *, check: bool = ...) -> Func: ...
    def CONCAT(self, text: _Value, /, *more: _Value, check: bool = ...) -> Func: ...
    def TEXTJOIN(
        self, delimiter: _Value, ignore_empty: _Value, text: _Value, /, *more: _Value, check: bool = ...
    ) -> Func: ...

    # -- dates ------------------------------------------------------------------
    def TODAY(self, *, check: bool = ...) -> Func: ...
    def NOW(self, *, check: bool = ...) -> Func: ...
    def DATE(self, year: _Value, month: _Value, day: _Value, /, *, check: bool = ...) -> Func: ...
    def TIME(self, hour: _Value, minute: _Value, second: _Value, /, *, check: bool = ...) -> Func: ...
    def YEAR(self, serial: _Value, /, *, check: bool = ...) -> Func: ...
    def MONTH(self, serial: _Value, /, *, check: bool = ...) -> Func: ...
    def DAY(self, serial: _Value, /, *, check: bool = ...) -> Func: ...
    def EOMONTH(self, start: _Value, months: _Value, /, *, check: bool = ...) -> Func: ...
    def EDATE(self, start: _Value, months: _Value, /, *, check: bool = ...) -> Func: ...
    def DATEDIF(self, start: _Value, end: _Value, unit: _Value, /, *, check: bool = ...) -> Func: ...

    # -- finance ----------------------------------------------------------------
    def NPV(self, rate: _Value, value: _Value, /, *values: _Value, check: bool = ...) -> Func: ...
    def IRR(self, values: Expr, guess: _Value = ..., /, *, check: bool = ...) -> Func: ...
    def XNPV(self, rate: _Value, values: Expr, dates: Expr, /, *, check: bool = ...) -> Func: ...
    def XIRR(self, values: Expr, dates: Expr, guess: _Value = ..., /, *, check: bool = ...) -> Func: ...
    def PMT(
        self, rate: _Value, nper: _Value, pv: _Value, fv: _Value = ..., type: _Value = ..., /, *, check: bool = ...
    ) -> Func: ...
    def PV(
        self, rate: _Value, nper: _Value, pmt: _Value, fv: _Value = ..., type: _Value = ..., /, *, check: bool = ...
    ) -> Func: ...
    def FV(
        self, rate: _Value, nper: _Value, pmt: _Value, pv: _Value = ..., type: _Value = ..., /, *, check: bool = ...
    ) -> Func: ...
    def NPER(
        self, rate: _Value, pmt: _Value, pv: _Value, fv: _Value = ..., type: _Value = ..., /, *, check: bool = ...
    ) -> Func: ...

    # -- information ------------------------------------------------------------
    def ISBLANK(self, value: _Value, /, *, check: bool = ...) -> Func: ...
    def ISNUMBER(self, value: _Value, /, *, check: bool = ...) -> Func: ...
    def ISTEXT(self, value: _Value, /, *, check: bool = ...) -> Func: ...
    def ISERROR(self, value: _Value, /, *, check: bool = ...) -> Func: ...
    def ISNA(self, value: _Value, /, *, check: bool = ...) -> Func: ...
    def NA(self, *, check: bool = ...) -> Func: ...

    # Any other name -- add-ins, functions newer than this stub -- stays callable
    # with any arguments.  This is what keeps the open set open.
    def __getattr__(self, name: str) -> Callable[..., Func]: ...
    def __dir__(self) -> list[str]: ...

F: _Functions
